### PR TITLE
1st commit and setup

### PR DESCRIPTION
**Pull request by iamtylerd**

### CODE REVIEW

**Comment by iamtylerd** [comment]
Basic quiz complete

**Comment by iamtylerd** [comment]
@c-stein

**Comment by C-Stein** [comment]
Nice work @iamtylerd. It's clear you understand the basic concepts. There are a couple of tweaks I'd like  you to make before merging-
1- Please make sure that a usage message is returned if the program is called without an argument

2- Please look carefully at your indentation in both js files. Clear indentation make code so much easier to read

3-  I'm curious why you decided to assign your entire stream.pipe... to a variable, and why you wrote a separate module for your writeStream instead of just .pipe(stdout). If you feel strongly about these, could you please talk me through your reasoning?

**Comment by iamtylerd** [comment]
1. Done
2. Should be corrected.
3.  I tend to over-use vars and classes in css.  I do this to future proof my stuff in a sense of being able to manipulate anything.
4. See 3

@c-stein

**Comment by C-Stein** [comment]
👍

**Pull request merged**
